#!/usr/bin/env bash
set -o errexit  # abort when any commands exits with error
set -o pipefail # abort when any command in a pipe exits with error
set -o nounset  # abort when any unset variable is used
set -o noglob # prevent bash from expanding glob
set -o errtrace # inherits trap on ERR in function and subshell
trap 'echo status:$? line:$LINENO line:$BASH_LINENO command:"$BASH_COMMAND" functions:$(printf " %s" ${FUNCNAME[@]:-})' ERR
if [[ "${trace:=0}" -eq 1 ]];then
  PS4='${LINENO}: '
  set -x
  export trace
fi

# jq -n -c \
#   --arg id "$RANDOM" \
#   '{
#   command:"create",
#   id:$id,
#   mass:1,
#   size:[5,5,5],
#   pos:[0,0,20]
# }' \
#   | socat - TCP:localhost:9999

echo -ne "\
{\"command\":\"create\",\"id\":\"${RANDOM}\",\"mass\":10,\"size\":[10,10,10],\"pos\":[0,0,20]}
{\"command\":\"create\",\"id\":\"${RANDOM}\",\"mass\":10,\"size\":[1,1,1],\"pos\":[1,0,19]}
{\"command\":\"create\",\"id\":\"${RANDOM}\",\"mass\":10,\"size\":[3,1,1],\"pos\":[0,0,20]}
" \
 | socat - TCP:localhost:9999


