#!/usr/bin/env bash
set -o errexit  # abort when any commands exits with error
set -o pipefail # abort when any command in a pipe exits with error
set -o nounset  # abort when any unset variable is used
set -o noglob # prevent bash from expanding glob
set -o errtrace # inherits trap on ERR in function and subshell
trap 'echo status:$? line:$LINENO line:$BASH_LINENO command:"$BASH_COMMAND" functions:$(printf " %s" ${FUNCNAME[@]:-})' ERR
if [[ "${trace:=0}" -eq 1 ]];then
  PS4='${LINENO}: '
  set -x
  export trace
fi

# jq -n -c \
#   --arg id "$RANDOM" \
#   '{
#   command:"create",
#   id:$id,
#   mass:1,
#   size:[5,5,5],
#   pos:[0,0,20]
# }' \
#   | socat - TCP:localhost:9999

if [[ "$#" -eq 0 ]];then
  :
  ${0} help

elif [[ "$1" == "help" ]];then shift
  which bash_scripts >/dev/null && bash_scripts show_commands ${0}

elif [ "$1" = "base" ];then shift ##
  echo -ne "\
{\"command\":\"create\",\"id\":\"${RANDOM}\",\"mass\":0,\"size\":[30,30,10],\"pos\":[0,0,-10]}
" \
 | socat - TCP:localhost:9999

elif [ "$1" = "single" ];then shift ##
  id="$1"; shift
  echo -ne "\
{\"command\":\"create\",\"id\":\"${id}\",\"mass\":1,\"size\":[1,1,1],\"pos\":[0,0,10]}
" \
 | socat - TCP:localhost:9999

elif [ "$1" = "joint" ];then shift ##
  id1="${RANDOM}1"
  id2="${RANDOM}2"
  echo -ne "\
{\"command\":\"create\",\"id\":\"${id1}\",\"mass\":1,\"size\":[1,1,3],\"pos\":[0,0,10]}
{\"command\":\"create\",\"id\":\"${id2}\",\"mass\":1,\"size\":[1,1,3],\"pos\":[0,0,10]}
{\"command\":\"joint\",\"id1\":\"${id1}\",\"id2\":\"${id2}\",\"pos1\":[0,0,1.5],\"pos2\":[0,0,-1.5]}
" \
 | socat - TCP:localhost:9999

elif [ "$1" = "delete" ];then shift ##
  id="$1"; shift
  echo -ne "\
{\"command\":\"delete\",\"id\":\"${id}\"}
" \
 | socat - TCP:localhost:9999

elif [ "$1" = "set" ];then shift ##
  : ${id="sleep_time"}
  : ${value="100"}
  echo -ne "\
{\"command\":\"set\",\"id\":\"${id}\",\"value\":${value}}
" \
 | socat - TCP:localhost:9999

elif [ "$1" = "stack" ];then shift ##
  echo -ne "\
{\"command\":\"create\",\"id\":\"${RANDOM}\",\"mass\":1,\"size\":[1,1,1],\"pos\":[0,0,20]}
{\"command\":\"create\",\"id\":\"${RANDOM}\",\"mass\":1,\"size\":[1,1,1],\"pos\":[0,0,21]}
{\"command\":\"create\",\"id\":\"${RANDOM}\",\"mass\":1,\"size\":[1,1,1],\"pos\":[0,0,22]}
{\"command\":\"create\",\"id\":\"${RANDOM}\",\"mass\":1,\"size\":[1,1,1],\"pos\":[0,0,23]}
" \
 | socat - TCP:localhost:9999

fi
