version: '3'
services:

  bullet:
    image: nasoym/bullet_container
    volumes:
      - .:/cmake_bullet
    ports:
      - 9999:9999
    tty: true
    command: /cmake_bullet/docker.sh



  rabbit:
    image: activiti/rabbitmq-stomp
    ports:
      - 5672:5672 
      - 15672:15672
      - 15674:15674 


