version: '3'
services:

  bullet:
    image: nasoym/bullet_container
    volumes:
      - .:/cmake_bullet
    ports:
      - 9999:9999
    tty: true
    depends_on:
      - rabbit
    command: /cmake_bullet/docker.sh

  html:
    image: httpd
    ports:
     - 8080:80 
    volumes:
      - ./html/:/usr/local/apache2/htdocs/ 

  rabbit:
    image: activiti/rabbitmq-stomp
    ports:
      - 15672:15672
      - 15674:15674 
      - 5672:5672 


