version: '3'
services:

  bullet:
    image: nasoym/bullet_container
    volumes:
      - .:/cmake_bullet
    ports:
      - 9999:9999
    tty: true
    depends_on:
      - rabbit
    command: /cmake_bullet/docker.sh

  html:
    image: httpd
    ports:
     - 8080:80 
    volumes:
      - ./html/:/usr/local/apache2/htdocs/ 

  debug_bodies:
    image: python:3.7-alpine
    volumes:
      - ./src:/src
      - ./debug_bodies:/debug_bodies
    command: /bin/sh -c 'apk update; apk add jq; pip3 install pika; while true; do jq -c "." /debug_bodies/debug_bodies.json | rabbit_queue="debug_bodies" rabbit_host="rabbit" python3 /src/python_pika_write.py; sleep 0.2; done'

  rabbit:
    image: activiti/rabbitmq-stomp
    ports:
      - 15672:15672
      - 15674:15674 
      - 5672:5672 


