#!/usr/bin/env bash
set -o errexit  # abort when any commands exits with error
set -o pipefail # abort when any command in a pipe exits with error
set -o nounset  # abort when any unset variable is used
set -o noglob # prevent bash from expanding glob
set -o errtrace # inherits trap on ERR in function and subshell
trap 'echo status:$? line:$LINENO line:$BASH_LINENO command:"$BASH_COMMAND" functions:$(printf " %s" ${FUNCNAME[@]:-})' ERR
if [[ "${trace:=0}" -eq 1 ]];then
  PS4='${LINENO}: '
  set -x
  export trace
fi

# jq -n -c \
#   --arg id "$RANDOM" \
#   '{
#   command:"create",
#   id:$id,
#   mass:1,
#   size:[5,5,5],
#   pos:[0,0,20]
# }' \
#   | socat - TCP:localhost:9999

if [[ "$#" -eq 0 ]];then
  :
  ${0} help

elif [[ "$1" == "help" ]];then shift
  which bash_scripts >/dev/null && bash_scripts show_commands ${0}

elif [ "$1" = "docker" ];then shift ##
  docker run --name rabbit -d -p 5672:5672 -p 15672:15672 -p 15674:15674 activiti/rabbitmq-stomp

elif [ "$1" = "run" ];then shift ##
  socat TCP-LISTEN:9999,reuseaddr,fork STDOUT | ./build_cmake/hello \
    | python3 src/python_pika_write.py

elif [ "$1" = "run_docker" ];then shift ##
  socat TCP-LISTEN:9999,reuseaddr,fork STDOUT \
    | ./build/hello \
    | rabbit_host="rabbit" python3 src/python_pika_write.py

elif [ "$1" = "build" ];then shift ##
  rm -rf build_cmake
  mkdir -p build_cmake 
  cd build_cmake 
  cmake ../ 
  make


elif [ "$1" = "base" ];then shift ##
  echo -ne "\
{\"command\":\"create\",\"id\":\"${RANDOM}\",\"mass\":0,\"size\":[200,200,10],\"pos\":[0,0,-10]}
" \
 | socat - TCP:localhost:9999

elif [ "$1" = "single" ];then shift ##
  id="$1"; shift
  echo -ne "\
{\"command\":\"create\",\"id\":\"${id}\",\"mass\":1,\"size\":[1,1,1],\"pos\":[0,0,10]}
" \
 | socat - TCP:localhost:9999

elif [ "$1" = "impulse" ];then shift ##
  id="$1"; shift
  echo -ne "\
{\"command\":\"body_impulse\",\"id\":\"${id}\",\"force\":[0,0,50]}
" \
 | socat - TCP:localhost:9999

elif [ "$1" = "joint_find_body" ];then shift ##
  id="$1"; shift
  echo -ne "\
{\"command\":\"joint_find_body\",\"id\":\"${id}\"}
" \
 | socat - TCP:localhost:9999

elif [ "$1" = "list_joints" ];then shift ##
  echo -ne "\
{\"command\":\"list_joints\"}
" \
 | socat - TCP:localhost:9999

elif [ "$1" = "joint" ];then shift ##
  id="${RANDOM}"
  id1="${RANDOM}1"
  id2="${RANDOM}2"
  echo -ne "\
{\"command\":\"create\",\"id\":\"${id1}\",\"mass\":1,\"size\":[1,2,4],\"pos\":[10,10,16]}
{\"command\":\"create\",\"id\":\"${id2}\",\"mass\":1,\"size\":[1,2,4],\"pos\":[10,10,14]}
{\"command\":\"joint\",\"id\":\"${id}\",\"id1\":\"${id1}\",\"id2\":\"${id2}\",\"pos1\":[0,0,2],\"rot1\":[0,0,0,1],\"pos2\":[0,0,-2],\"rot2\":[0,0,0,1],\"limits\":[0.0,1.5,1.5, 1.0,0.3,1.0],\"damping\":0.01}
" \
 | socat - TCP:localhost:9999
# {\"command\":\"joint\",\"id1\":\"${id1}\",\"id2\":\"${id2}\",\"pos1\":[0,0,1.5],\"pos2\":[0,0,-1.5],\"limitlower\":[0,1,0],\"limitupper\":[0,-1,0]}
# {\"command\":\"joint2\",\"id1\":\"${id1}\",\"id2\":\"${id2}\",\"pos1\":[0,0,2],\"rot1\":[0,0,0,1],\"pos2\":[0,0,-2],\"rot2\":[0,0,0,1],\"limits\":[0,1.6,0.1,1.0,0.3,1.0],\"damping\":0.01}

echo "$id $id1 $id2"

elif [ "$1" = "joint_limit" ];then shift ##
  id="$1"; shift
  echo -ne "\
{\"command\":\"joint_limit\",\"id\":\"${id}\",\"limits\":[0.0,0.5,1.5,1.0,0.3,1.0]}
" \
 | socat - TCP:localhost:9999

elif [ "$1" = "joint_motor_off" ];then shift ##
  id="$1"; shift
  echo -ne "\
{\"command\":\"joint_motor\",\"id\":\"${id}\",\"enable\":false,\"impulse\":0.1,\"target\":[0,0,0,1]}
" \
 | socat - TCP:localhost:9999
# {\"command\":\"joint_motor\",\"id\":\"${id}\",\"enable\":true,\"impulse\":0.1,\"target\":[0.5,0.5,0.5,0.5]}

elif [ "$1" = "joint_motor" ];then shift ##
  id="$1"; shift
  echo -ne "\
{\"command\":\"joint_motor\",\"id\":\"${id}\",\"enable\":true,\"impulse\":1.5,\"target\":[0,0,0,1]}
" \
 | socat - TCP:localhost:9999
# {\"command\":\"joint_motor\",\"id\":\"${id}\",\"enable\":true,\"impulse\":0.1,\"target\":[0.5,0.5,0.5,0.5]}

elif [ "$1" = "joint_delete" ];then shift ##
  id="$1"; shift
  echo -ne "\
{\"command\":\"delete_joint\",\"id\":\"${id}\"}
" \
 | socat - TCP:localhost:9999

elif [ "$1" = "delete" ];then shift ##
  id="$1"; shift
  echo -ne "\
{\"command\":\"delete\",\"id\":\"${id}\"}
" \
 | socat - TCP:localhost:9999

elif [ "$1" = "clear" ];then shift ##
  echo -ne "\
{\"command\":\"clear\"}
" \
 | socat - TCP:localhost:9999

elif [ "$1" = "set" ];then shift ##
  # : ${id="sleep_time"}
  # : ${value="100"}
  id="$1";shift
  value="$1"; shift
  echo -ne "\
{\"command\":\"set\",\"id\":\"${id}\",\"value\":${value}}
" \
 | socat - TCP:localhost:9999

elif [ "$1" = "stack" ];then shift ##
  echo -ne "\
{\"command\":\"create\",\"id\":\"${RANDOM}\",\"mass\":1,\"size\":[1,1,1],\"pos\":[0,0,20]}
{\"command\":\"create\",\"id\":\"${RANDOM}\",\"mass\":1,\"size\":[1,1,1],\"pos\":[0,0,21]}
{\"command\":\"create\",\"id\":\"${RANDOM}\",\"mass\":1,\"size\":[1,1,1],\"pos\":[0,0,22]}
{\"command\":\"create\",\"id\":\"${RANDOM}\",\"mass\":1,\"size\":[1,1,1],\"pos\":[0,0,23]}
{\"command\":\"create\",\"id\":\"${RANDOM}\",\"mass\":1,\"size\":[1,1,1],\"pos\":[0,0,24]}
{\"command\":\"create\",\"id\":\"${RANDOM}\",\"mass\":1,\"size\":[1,1,1],\"pos\":[0,0,25]}
{\"command\":\"create\",\"id\":\"${RANDOM}\",\"mass\":1,\"size\":[1,1,1],\"pos\":[0,0,26]}
{\"command\":\"create\",\"id\":\"${RANDOM}\",\"mass\":1,\"size\":[1,1,1],\"pos\":[0,0,27]}
{\"command\":\"create\",\"id\":\"${RANDOM}\",\"mass\":1,\"size\":[1,1,1],\"pos\":[0,0,28]}
" \
 | socat - TCP:localhost:9999

fi
